name: 'Setup'
description: 'Setup java and xvfb'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #v4.7.1
      with:
        distribution: temurin
        java-version: '21'
    - name: Cache local Maven repository
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 #v4.2.4
      with:
        path: |
          ~/.m2/repository
          net.sourceforge.pmd.eclipse.plugin/japicmp-data
        # re-cache on changes in the pom and target files
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Setup xvfb
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        #see https://github.com/GabrielBB/xvfb-action
        sudo apt-get install --yes xvfb
        sudo apt-get install --yes libgtk2.0-0
        echo 'xvfb_cmd=xvfb-run --auto-servernum' >> "$GITHUB_ENV"
