name: build

on:
  push:
    branches:
      - main
      - master
    tags:
      - '**'
  pull_request:
  schedule:
    # build it monthly: At 05:00 on day-of-month 1.
    - cron:  '0 5 1 * *'
  workflow_dispatch:

jobs:
  # verify build on one node before multiple builds on different os are started
  fail-fast-build:
    name: verify (ubuntu-latest, 2023-03)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: ./.github/actions/build
        with:
          targetPlatform: 2023-03
          pmdCiSecretPassphrase: ${{ secrets.PMD_CI_SECRET_PASSPHRASE }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}


  build:
    needs: fail-fast-build
    name: verify (${{ matrix.os }}, ${{ matrix.targetPlatform }})
    timeout-minutes: 60
    continue-on-error: false

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        targetPlatform: [ 2023-03 ]
        exclude:
          # exclude the fail-fast-build, which already ran
          - os: ubuntu-latest
            targetPlatform: 2023-03
        # run other target platforms only on linux
        include:
          - os: ubuntu-latest
            targetPlatform: 2022-12
          - os: ubuntu-latest
            targetPlatform: 2022-09
          - os: ubuntu-latest
            targetPlatform: 2022-06
      fail-fast: true

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - uses: ./.github/actions/build
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          pmdCiSecretPassphrase: ${{ secrets.PMD_CI_SECRET_PASSPHRASE }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
